# CLKS
set_property PACKAGE_PIN M19 [get_ports PL_CLK_100MHz]
set_property PACKAGE_PIN L18 [get_ports clk_prog_clk0]
set_property PACKAGE_PIN Y9 [get_ports clk_prog_clk1]
set_property PACKAGE_PIN Y6 [get_ports clk_prog_clk2]

#create_clock -period 10.000 -name clk100MHZ [get_ports PL_CLK_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports PL_CLK_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_prog_clk0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_prog_clk1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_prog_clk2]

# sfp  ports
set_property PACKAGE_PIN A19 [get_ports SFP_TX_Fault]
set_property PACKAGE_PIN A18 [get_ports SFP_TX_DIS]
set_property PACKAGE_PIN A22 [get_ports SFP_SDA]
set_property PACKAGE_PIN A21 [get_ports SFP_SCL]
set_property PACKAGE_PIN B22 [get_ports SFP_PRESENT]
set_property PACKAGE_PIN B21 [get_ports SFP_Rate_Select]
set_property PACKAGE_PIN C22 [get_ports SFP_LOS]

set_property IOSTANDARD LVCMOS33 [get_ports SFP_TX_Fault]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_TX_DIS]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_PRESENT]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_Rate_Select]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_LOS]

# LS_ADC2 & LS_ADC1 PINS
set_property PACKAGE_PIN R20 [get_ports {LS_ADC2_DB[13]}]
set_property PACKAGE_PIN R21 [get_ports {LS_ADC2_DB[12]}]
set_property PACKAGE_PIN P18 [get_ports {LS_ADC2_DB[11]}]
set_property PACKAGE_PIN P17 [get_ports {LS_ADC2_DB[10]}]
set_property PACKAGE_PIN R16 [get_ports {LS_ADC2_DB[9]}]
set_property PACKAGE_PIN P16 [get_ports {LS_ADC2_DB[8]}]
set_property PACKAGE_PIN N20 [get_ports {LS_ADC2_DB[7]}]
set_property PACKAGE_PIN N19 [get_ports {LS_ADC2_DB[6]}]
set_property PACKAGE_PIN P22 [get_ports {LS_ADC2_DB[5]}]
set_property PACKAGE_PIN N22 [get_ports {LS_ADC2_DB[4]}]
set_property PACKAGE_PIN M21 [get_ports {LS_ADC2_DB[3]}]
set_property PACKAGE_PIN M22 [get_ports {LS_ADC2_DB[2]}]
set_property PACKAGE_PIN J20 [get_ports {LS_ADC2_DB[1]}]
set_property PACKAGE_PIN K21 [get_ports {LS_ADC2_DB[0]}]
set_property PACKAGE_PIN J21 [get_ports LS_ADC2_CLK]
set_property PACKAGE_PIN J22 [get_ports LS_ADC2_OTR]

set_property PACKAGE_PIN P15 [get_ports {LS_ADC1_DB[13]}]
set_property PACKAGE_PIN N15 [get_ports {LS_ADC1_DB[12]}]
set_property PACKAGE_PIN Y11 [get_ports {LS_ADC1_DB[11]}]
set_property PACKAGE_PIN Y10 [get_ports {LS_ADC1_DB[10]}]
set_property PACKAGE_PIN V10 [get_ports {LS_ADC1_DB[9]}]
set_property PACKAGE_PIN V9 [get_ports {LS_ADC1_DB[8]}]
set_property PACKAGE_PIN T17 [get_ports {LS_ADC1_DB[7]}]
set_property PACKAGE_PIN T16 [get_ports {LS_ADC1_DB[6]}]
set_property PACKAGE_PIN V12 [get_ports {LS_ADC1_DB[5]}]
set_property PACKAGE_PIN W12 [get_ports {LS_ADC1_DB[4]}]
set_property PACKAGE_PIN W10 [get_ports {LS_ADC1_DB[3]}]
set_property PACKAGE_PIN W11 [get_ports {LS_ADC1_DB[2]}]
set_property PACKAGE_PIN AA9 [get_ports {LS_ADC1_DB[1]}]
set_property PACKAGE_PIN AA8 [get_ports {LS_ADC1_DB[0]}]
set_property PACKAGE_PIN R18 [get_ports LS_ADC1_CLK]
set_property PACKAGE_PIN T18 [get_ports LS_ADC1_OTR]


set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC2_OTR]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC1_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC1_OTR]

# LS_DAC2 & LS_DAC1 PINS

set_property PACKAGE_PIN W8 [get_ports {LS_DAC2_DB[13]}]
set_property PACKAGE_PIN V8 [get_ports {LS_DAC2_DB[12]}]
set_property PACKAGE_PIN U10 [get_ports {LS_DAC2_DB[11]}]
set_property PACKAGE_PIN U9 [get_ports {LS_DAC2_DB[10]}]
set_property PACKAGE_PIN AB11 [get_ports {LS_DAC2_DB[9]}]
set_property PACKAGE_PIN AA11 [get_ports {LS_DAC2_DB[8]}]
set_property PACKAGE_PIN AB10 [get_ports {LS_DAC2_DB[7]}]
set_property PACKAGE_PIN AB9 [get_ports {LS_DAC2_DB[6]}]
set_property PACKAGE_PIN W6 [get_ports {LS_DAC2_DB[5]}]
set_property PACKAGE_PIN W5 [get_ports {LS_DAC2_DB[4]}]
set_property PACKAGE_PIN AA4 [get_ports {LS_DAC2_DB[3]}]
set_property PACKAGE_PIN Y4 [get_ports {LS_DAC2_DB[2]}]
set_property PACKAGE_PIN V5 [get_ports {LS_DAC2_DB[1]}]
set_property PACKAGE_PIN V4 [get_ports {LS_DAC2_DB[0]}]
set_property PACKAGE_PIN Y5 [get_ports LS_DAC2_WRT]
set_property PACKAGE_PIN V7 [get_ports LS_DAC2_CLK]
set_property PACKAGE_PIN W7 [get_ports LS_DAC_MODE]

set_property PACKAGE_PIN K15 [get_ports {LS_DAC1_DB[13]}]
set_property PACKAGE_PIN J15 [get_ports {LS_DAC1_DB[12]}]
set_property PACKAGE_PIN K19 [get_ports {LS_DAC1_DB[11]}]
set_property PACKAGE_PIN K20 [get_ports {LS_DAC1_DB[10]}]
set_property PACKAGE_PIN D15 [get_ports {LS_DAC1_DB[9]}]
set_property PACKAGE_PIN E15 [get_ports {LS_DAC1_DB[8]}]
set_property PACKAGE_PIN E19 [get_ports {LS_DAC1_DB[7]}]
set_property PACKAGE_PIN E20 [get_ports {LS_DAC1_DB[6]}]
set_property PACKAGE_PIN D16 [get_ports {LS_DAC1_DB[5]}]
set_property PACKAGE_PIN D17 [get_ports {LS_DAC1_DB[4]}]
set_property PACKAGE_PIN H19 [get_ports {LS_DAC1_DB[3]}]
set_property PACKAGE_PIN H20 [get_ports {LS_DAC1_DB[2]}]
set_property PACKAGE_PIN F17 [get_ports {LS_DAC1_DB[1]}]
set_property PACKAGE_PIN G17 [get_ports {LS_DAC1_DB[0]}]
set_property PACKAGE_PIN G16 [get_ports LS_DAC1_WRT]
set_property PACKAGE_PIN G15 [get_ports LS_DAC1_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC2_WRT]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC1_WRT]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC1_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC_MODE]



# Audio AD Pins
set_property PACKAGE_PIN AB6 [get_ports Audio_AD_SDOUT]
set_property PACKAGE_PIN AB2 [get_ports Audio_AD_SCLK]
set_property PACKAGE_PIN Y8 [get_ports Audio_AD_nRST]
set_property PACKAGE_PIN AB7 [get_ports Audio_AD_MCLK]
set_property PACKAGE_PIN AB4 [get_ports Audio_AD_M1]
set_property PACKAGE_PIN AB5 [get_ports Audio_AD_M0]
set_property PACKAGE_PIN AB1 [get_ports Audio_AD_LRCK]

set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_SDOUT]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_M1]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_M0]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_LRCK]

# Audio DA Pins
set_property PACKAGE_PIN U6 [get_ports Audio_DA_SDIN]
set_property PACKAGE_PIN U5 [get_ports Audio_DA_SCLK]
set_property PACKAGE_PIN U4 [get_ports Audio_DA_LRCL]
set_property PACKAGE_PIN T4 [get_ports Audio_DA_MCLK]

set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_SDIN]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_LRCL]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_MCLK]

# 88E1512 Pins
set_property PACKAGE_PIN C18 [get_ports {ETH_PL_RXD[3]}]
set_property PACKAGE_PIN C17 [get_ports {ETH_PL_RXD[2]}]
set_property PACKAGE_PIN B17 [get_ports {ETH_PL_RXD[1]}]
set_property PACKAGE_PIN B16 [get_ports {ETH_PL_RXD[0]}]
set_property PACKAGE_PIN D18 [get_ports ETH_PL_RXCK]
set_property PACKAGE_PIN C19 [get_ports ETH_PL_RXCTL]

set_property PACKAGE_PIN G20 [get_ports {ETH_PL_TXD[3]}]
set_property PACKAGE_PIN G21 [get_ports {ETH_PL_TXD[2]}]
set_property PACKAGE_PIN F21 [get_ports {ETH_PL_TXD[1]}]
set_property PACKAGE_PIN F22 [get_ports {ETH_PL_TXD[0]}]
set_property PACKAGE_PIN D20 [get_ports ETH_PL_TXCK]
set_property PACKAGE_PIN C20 [get_ports ETH_PL_TXCTL]

set_property PACKAGE_PIN A17 [get_ports ETH_PL_MDIO]
set_property PACKAGE_PIN A16 [get_ports ETH_PL_MDC]
set_property PACKAGE_PIN H18 [get_ports ETH_PL_nRST]

set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_TXCTL]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_TXCK]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_RXCTL]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_RXCK]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_MDIO]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_nRST]

# RTL8211E Pins  PS

# LEDs
#  set_property PACKAGE_PIN F18 [ get_ports LED_D17 ]
#  set_property PACKAGE_PIN E18 [ get_ports LED_D16 ]
#  set_property PACKAGE_PIN F16 [ get_ports LED_D15 ]
#  set_property PACKAGE_PIN E16 [ get_ports LED_D14 ]

#  set_property IOSTANDARD LVCMOS33  [ get_ports LED_D17 ]
#  set_property IOSTANDARD LVCMOS33  [ get_ports LED_D16 ]
#  set_property IOSTANDARD LVCMOS33  [ get_ports LED_D15 ]
#  set_property IOSTANDARD LVCMOS33  [ get_ports LED_D14 ]


#  GPIOS Pins

#  set_property PACKAGE_PIN M20  [ get_ports GPIO_J9_20 ]  # J9_20
#  set_property PACKAGE_PIN H22  [ get_ports GPIO_J9_18 ]  # J9_18
#  set_property PACKAGE_PIN R6   [ get_ports GPIO_J9_17 ]  # J9_17
#  set_property PACKAGE_PIN T6   [ get_ports GPIO_J9_15 ]  # J9_15
#  set_property PACKAGE_PIN B20  [ get_ports GPIO_J9_14 ]  # J9_14
#  set_property PACKAGE_PIN AA6  [ get_ports GPIO_J9_13 ]  # J9_13
#  set_property PACKAGE_PIN H17  [ get_ports GPIO_J9_12 ]  # J9_12
#  set_property PACKAGE_PIN R7   [ get_ports GPIO_J9_10 ]  # J9_10
#  set_property PACKAGE_PIN U7   [ get_ports GPIO_J9_08 ]  # J9_08

set_property PACKAGE_PIN L22  [get_ports GPIO_TH1]
set_property PACKAGE_PIN AA12 [get_ports GPIO_TH2]
set_property PACKAGE_PIN AB12 [get_ports GPIO_TH3]
set_property PACKAGE_PIN D21  [get_ports GPIO_TH4]
set_property PACKAGE_PIN L21  [get_ports GPIO_TH5]
set_property PACKAGE_PIN R7   [get_ports GPIO_TH6]
set_property PACKAGE_PIN U7   [get_ports GPIO_TH7]
set_property PACKAGE_PIN T6   [get_ports GPIO_TH8]
set_property PACKAGE_PIN L19  [get_ports GPIO_TH9]
set_property PACKAGE_PIN J18  [get_ports GPIO_TH10]

set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH1]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH2]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH3]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH4]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH5]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH6]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH7]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH8]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH9]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH10]

# DSP PINS
set_property PACKAGE_PIN E21 [get_ports McBSP0_CLKS0]
set_property PACKAGE_PIN F19 [get_ports McBSP0_CLKX0]
set_property PACKAGE_PIN G19 [get_ports McBSP0_FSX0]
set_property PACKAGE_PIN J17 [get_ports McBSP0_DX0]
set_property PACKAGE_PIN J16 [get_ports McBSP0_FSR0]
set_property PACKAGE_PIN M17 [get_ports McBSP0_DR0]
set_property PACKAGE_PIN R19 [get_ports McBSP1_DX1]

set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_CLKS0]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_CLKX0]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_FSX0]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_DX0]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_FSR0]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_DR0]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP1_DX1]

# AD9361 PINS
set_property PACKAGE_PIN AB19 [get_ports {AD9361_P0_D[11]}]
set_property PACKAGE_PIN AB20 [get_ports {AD9361_P0_D[10]}]
set_property PACKAGE_PIN AB21 [get_ports {AD9361_P0_D[9]}]
set_property PACKAGE_PIN AA21 [get_ports {AD9361_P0_D[8]}]
set_property PACKAGE_PIN AB22 [get_ports {AD9361_P0_D[7]}]
set_property PACKAGE_PIN AA22 [get_ports {AD9361_P0_D[6]}]
set_property PACKAGE_PIN Y20 [get_ports {AD9361_P0_D[5]}]
set_property PACKAGE_PIN Y21 [get_ports {AD9361_P0_D[4]}]
set_property PACKAGE_PIN W22 [get_ports {AD9361_P0_D[3]}]
set_property PACKAGE_PIN V22 [get_ports {AD9361_P0_D[2]}]
set_property PACKAGE_PIN U22 [get_ports {AD9361_P0_D[1]}]
set_property PACKAGE_PIN T22 [get_ports {AD9361_P0_D[0]}]

set_property PACKAGE_PIN AB14 [get_ports {AD9361_P1_D[11]}]
set_property PACKAGE_PIN AB15 [get_ports {AD9361_P1_D[10]}]
set_property PACKAGE_PIN Y13 [get_ports {AD9361_P1_D[9]}]
set_property PACKAGE_PIN AA13 [get_ports {AD9361_P1_D[8]}]
set_property PACKAGE_PIN Y14 [get_ports {AD9361_P1_D[7]}]
set_property PACKAGE_PIN AA14 [get_ports {AD9361_P1_D[6]}]
set_property PACKAGE_PIN Y15 [get_ports {AD9361_P1_D[5]}]
set_property PACKAGE_PIN W15 [get_ports {AD9361_P1_D[4]}]
set_property PACKAGE_PIN AB16 [get_ports {AD9361_P1_D[3]}]
set_property PACKAGE_PIN AA16 [get_ports {AD9361_P1_D[2]}]
set_property PACKAGE_PIN AA19 [get_ports {AD9361_P1_D[1]}]
set_property PACKAGE_PIN Y19 [get_ports {AD9361_P1_D[0]}]

#  set_property PACKAGE_PIN AA17 [ get_ports AD9361_Ctrl_IN[3] ]
#  set_property PACKAGE_PIN U17  [ get_ports AD9361_Ctrl_IN[2] ]
#  set_property PACKAGE_PIN V17  [ get_ports AD9361_Ctrl_IN[1] ]
#  set_property PACKAGE_PIN W21  [ get_ports AD9361_Ctrl_IN[0] ]

set_property PACKAGE_PIN C15 [get_ports AD9361_rst]
set_property PACKAGE_PIN AA17 [get_ports AD9361_TX_FRAME]
set_property PACKAGE_PIN U17 [get_ports AD9361_RX_FRAME]
set_property PACKAGE_PIN W16 [get_ports AD9361_FBCLK]
set_property PACKAGE_PIN W17 [get_ports AD9361_DATACLK]
set_property PACKAGE_PIN U21 [get_ports AD9361_ENABLE]
set_property PACKAGE_PIN W21 [get_ports AD9361_SYNC_IN]
set_property PACKAGE_PIN V17 [get_ports AD9361_EN_AGC]
#  set_property PACKAGE_PIN U12  [ get_ports AD9361_UART_1_TX ]
#  set_property PACKAGE_PIN U11  [ get_ports AD9361_UART_1_RX ]
set_property PACKAGE_PIN W20 [get_ports AD9361_TXNRX]
#  set_property PACKAGE_PIN B15  [ get_ports AD9361_PLLT_CLK_OUT ]    # not used
#  set_property PACKAGE_PIN V14  [ get_ports AD9361_PLL_B_OUT_P ]     # not used
#  set_property PACKAGE_PIN V15  [ get_ports AD9361_PLL_B_OUT_N ]     # not used

set_property PACKAGE_PIN AB17 [get_ports AD9361_SPI_CLK]
set_property PACKAGE_PIN U20 [get_ports AD9361_SPI_DI]
set_property PACKAGE_PIN V20 [get_ports AD9361_SPI_DO]
set_property PACKAGE_PIN AA18 [get_ports AD9361_SPI_ENB]
set_property PACKAGE_PIN V19 [get_ports AD9361_SPI_SEL]


set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P0_D[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9361_P1_D[0]}]

#  set_property IOSTANDARD LVCMOS18 [ get_ports AD9361_Ctrl_IN[3] ]
#  set_property IOSTANDARD LVCMOS18 [ get_ports AD9361_Ctrl_IN[2] ]
#  set_property IOSTANDARD LVCMOS18 [ get_ports AD9361_Ctrl_IN[1] ]
#  set_property IOSTANDARD LVCMOS18 [ get_ports AD9361_Ctrl_IN[0] ]

set_property IOSTANDARD LVCMOS18 [get_ports AD9361_TX_FRAME]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_RX_FRAME]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_FBCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_DATACLK]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_ENABLE]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SYNC_IN]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_EN_AGC]
#  set_property IOSTANDARD LVCMOS33 [ get_ports AD9361_UART_1_TX ]
#  set_property IOSTANDARD LVCMOS33 [ get_ports AD9361_UART_1_RX ]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_TXNRX]
#  set_property IOSTANDARD LVCMOS33 [ get_ports AD9361_PLLT_CLK_OUT ]
#  set_property IOSTANDARD LVCMOS18 [ get_ports AD9361_PLL_B_OUT_P ]
#  set_property IOSTANDARD LVCMOS18 [ get_ports AD9361_PLL_B_OUT_N ]

set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_DI]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_DO]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_ENB]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_SEL]

set_property IOSTANDARD LVCMOS33 [get_ports AD9361_rst]

# other pins
set_property PACKAGE_PIN R15 [get_ports AD9361_10M_OUT]
set_property PACKAGE_PIN B19 [get_ports AD9361_10M_IN]

set_property IOSTANDARD LVCMOS33 [get_ports AD9361_10M_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports AD9361_10M_IN]

create_clock -period 32.552 -name AD9361_DATACLK [get_ports AD9361_DATACLK]
#create_clock -name CLK_B2B_FPGA_7 -period 32 [ get_ports CLK_B2B_FPGA_7_P ]
# create_clock -period 32.552 -name clk2AD9361 [get_pins inst_AD9361/AD9361_RX_CLK]


#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets AD9361_RX_FRAME]

set_input_delay 0.500 -max -clock AD9361_DATACLK [get_ports {AD9361_P0_D}]
set_input_delay -0.500 -min -clock AD9361_DATACLK [get_ports {AD9361_P0_D}]

set_output_delay -clock clk2AD9361 -max 0.500 [get_ports {AD9361_P1_D} ]
set_output_delay -clock clk2AD9361 -min -0.500 [get_ports {AD9361_P1_D} ]

